spring:
    application:
        name: kakao-oauth

    output:
      ansi:
        enabled: ALWAYS

    datasource:
      driver-class-name: org.h2.Driver
      url: "jdbc:h2:mem:kakaoauth_db"
      username: sa
      password:

    h2:
      console:
        enabled: true
        path: "/h2-console"